# Generated by Django 5.2.6 on 2025-09-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_clearancelevel_options_clearancelevel_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип Документа')),
            ],
            options={
                'verbose_name': 'Тип Документа',
                'verbose_name_plural': 'Типы Документов',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название Документа')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('updated_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата Обновления')),
                ('is_confidentional', models.BooleanField(default=False, verbose_name='Конфиденциальный')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Автор')),
                ('required_clearance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.clearancelevel', verbose_name='Уровень Допуска')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documentation.documenttype', verbose_name='Тип Документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-created_date'],
            },
        ),
    ]
