# Generated by Django 5.2.6 on 2025-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата Обновления'),
        ),
    ]
