# Generated by Django 5.2.6 on 2025-09-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_alter_documentation_updated_date'),
        ('employees', '0005_alter_division_options_alter_division_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentation',
            name='is_confidentional',
        ),
        migrations.AlterField(
            model_name='documentation',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Автор'),
        ),
    ]
