# Generated by Django 5.2.6 on 2026-02-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_remove_documentation_is_confidentional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='content',
            field=models.TextField(verbose_name='Содержание Документа'),
        ),
    ]
