# Generated by Django 5.2.6 on 2026-03-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_alter_documentation_content'),
        ('employees', '0007_alter_division_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='allowed_clusters',
            field=models.ManyToManyField(blank=True, to='employees.cluster', verbose_name='Доступ Кластерам'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, to='employees.department', verbose_name='Доступ Департаментам'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='allowed_divisions',
            field=models.ManyToManyField(blank=True, to='employees.division', verbose_name='Доступ Отделам'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='allowed_employees',
            field=models.ManyToManyField(blank=True, related_name='documentation_allowed', to='employees.employee', verbose_name='Доступ Сотрудникам'),
        ),
    ]
