# Generated by Django 5.2.6 on 2025-09-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_clearancelevel_options_clearancelevel_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Статус Исследования')),
            ],
            options={
                'verbose_name': 'Статус Исследования',
                'verbose_name_plural': 'Статусы Исследований',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название Исследования')),
                ('description', models.TextField(verbose_name='Содержание Исследования')),
                ('objectives', models.TextField(verbose_name='Цели Исследования')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('end_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата Обновления')),
                ('findings', models.TextField(verbose_name='Результаты Исследования')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Руководитель Исследования')),
                ('required_clearance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.clearancelevel', verbose_name='Уровень Допуска')),
                ('team', models.ManyToManyField(blank=True, related_name='research_team', to='employees.employee', verbose_name='Участники Исследования')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='research.researchstatus', verbose_name='Статус Исследования')),
            ],
            options={
                'verbose_name': 'Исследование',
                'verbose_name_plural': 'Исследования',
                'ordering': ['-start_date'],
            },
        ),
    ]
