# Generated by Django 5.2.6 on 2025-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['-created_date'], 'verbose_name': 'Исследование', 'verbose_name_plural': 'Исследования'},
        ),
        migrations.RenameField(
            model_name='research',
            old_name='start_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='research',
            name='end_date',
        ),
        migrations.AddField(
            model_name='research',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата Обновления'),
        ),
    ]
