# Generated by Django 5.2.6 on 2026-02-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_alter_research_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='research',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='research',
            name='objectives',
        ),
    ]
