# Generated by Django 5.2.6 on 2025-09-15 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Уровень Доступа')),
            ],
            options={
                'verbose_name': 'Уровень Доступа',
                'verbose_name_plural': 'Уровни Доступа',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кластер',
                'verbose_name_plural': 'Кластеры',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='employees.cluster', verbose_name='Кластеры')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='employees.department', verbose_name='Департаменты')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.cluster', verbose_name='Кластеры')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должность',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и Фамилия')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Фото')),
                ('clearance_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.clearancelevel', verbose_name='Уровень Доступа')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.division', verbose_name='Подразделение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['cluster', 'name'], name='employees_d_cluster_b8558b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'cluster')},
        ),
        migrations.AddIndex(
            model_name='division',
            index=models.Index(fields=['department', 'name'], name='employees_d_departm_80da61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('name', 'department')},
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['cluster', 'name'], name='employees_p_cluster_c1a485_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('name', 'cluster')},
        ),
    ]
