# Generated by Django 5.2.6 on 2025-09-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearancelevel',
            options={'verbose_name': 'Уровень Допуска', 'verbose_name_plural': 'Уровни Допуска'},
        ),
        migrations.AddField(
            model_name='clearancelevel',
            name='number',
            field=models.IntegerField(default=0, unique=True, verbose_name='Уровень Допуска'),
        ),
        migrations.AlterField(
            model_name='clearancelevel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='clearance_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.clearancelevel', verbose_name='Уровень Допуска'),
        ),
    ]
