# Generated by Django 5.2.6 on 2025-09-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_clearancelevel_options_clearancelevel_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearancelevel',
            name='name',
        ),
        migrations.AlterField(
            model_name='division',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='employees.department', verbose_name='Подразделения'),
        ),
    ]
