# Generated by Django 5.2.6 on 2025-09-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_clearancelevel_name_alter_division_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
    ]
