# Generated by Django 5.2.6 on 2025-09-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_position_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='division',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='employees.department', verbose_name='Отделы'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='clearance_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.clearancelevel', verbose_name='Уровень Допуска'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.division', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='position',
            name='cluster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='employees.cluster', verbose_name='Кластеры'),
        ),
    ]
