# Generated by Django 5.2.6 on 2025-10-13 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='employees.department', verbose_name='Департаменты'),
        ),
    ]
